services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superheroes
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myPassword
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
#  minio:
#    image: 'bitnami/minio:latest'
#    ports:
#      - 9000:9000
#      - 9001:9001
#    environment:
#      - MINIO_ROOT_USER=minio-root-user
#      - MINIO_ROOT_PASSWORD=minio-root-password
#      - MINIO_DEFAULT_BUCKETS=examillustrations,examphotos
#    networks:
#      - network
#    volumes:
#      - minio:/bitnami/minio/data
  back:
    image: back-exam
    ports:
      - 8448:8448
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      - spring.datasource.password=myPassword
      - spring.datasource.username=myUser
      - spring.datasource.url=jdbc:mysql://database:3306/superheroes
#      - s3.access_key=mv4YuliZ3286JxpPqPBm
#      - s3.secret_key=JpdgHkEJ0BA3DXTax1fK3nkrpj6rcFHkZgUSimrK
#      - s3.hostname=http://192.168.1.45:9000
    networks:
      - network
    healthcheck:
      test: curl http://localhost:8448/actuator/health
      interval: 10s
      timeout: 3s
      retries: 3
#  front:
#    image: front
#    ports:
#      - 8888:80
#    environment:
#      - BACKEND_URL=http://localhost:8080
#    networks:
#      - network


volumes:
  database:
#  minio:

networks:
  network: