services:
  database:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superheroes
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myPassword
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  back:
    image: back-exam
    ports:
      - 8448:8448
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      - spring.datasource.password=myPassword
      - spring.datasource.username=myUser
      - spring.datasource.url=jdbc:mysql://database:3306/superheroes
    networks:
      - network
    healthcheck:
      test: curl http://localhost:8448/actuator/health
      interval: 10s
      timeout: 3s
      retries: 3
  front:
    image: front-exam
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://localhost:8448
    networks:
      - network

volumes:
  database:

networks:
  network: