# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build push angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


defaults:
  run:
    working-directory: ./angular

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build --if-present




